/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reader;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.Reader;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;

public class App {

    public static void main(String[] args) throws IOException {
        try {
            Gson gson = new Gson();
            Reader reader = Files.newBufferedReader(Paths.get("./src/main/resources/recentquotes.json"));
            Writer writer = Files.newBufferedWriter(Paths.get("./src/main/resources/recentquotes00.json"));
            // i got this code from stackoverflow it worked for me but i did not understand how it works, https://stackoverflow.com/questions/43117731/what-is-type-typetoken
            ArrayList<Book> texts = new Gson().fromJson(reader, new TypeToken<ArrayList<Book>>() {}.getType());

            int randomQuote = (int) (Math.random() * ((texts.size()) + 1));
            System.out.println(texts.get(randomQuote).getAuthor() + " \n" + texts.get(randomQuote).getText());
            ((BufferedReader) reader).readLine();
            writer.write(gson.toJson(texts));
            reader.close();

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }
}

